# Generated by Django 5.0.7 on 2024-07-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.URLField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('release_year', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
