# Generated by Django 5.0.7 on 2024-07-17 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0002_remove_tool_interest_remove_tool_photo_and_more'),
        ('posts', '0002_remove_post_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tools',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devtools.tool'),
        ),
    ]
