# Generated by Django 5.0.7 on 2024-07-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True, verbose_name='수정일'),
        ),
    ]
