# Generated by Django 5.0.7 on 2024-07-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='marked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
