# Generated by Django 5.0.7 on 2024-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='제목')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='이미지')),
                ('content', models.CharField(max_length=100, verbose_name='설명')),
                ('interest', models.IntegerField(default=0, verbose_name='관심도')),
                ('tools', models.CharField(max_length=30, verbose_name='개발툴')),
            ],
        ),
    ]
