# Generated by Django 5.0.7 on 2024-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tools',
        ),
        migrations.AddField(
            model_name='tool',
            name='kinds',
            field=models.CharField(default='', max_length=30, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(max_length=24, verbose_name='이름'),
        ),
    ]
