# Generated by Django 5.0.7 on 2024-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0002_movie_actor_movie_director_movie_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to='media/'),
        ),
    ]
