# Generated by Django 5.0.7 on 2024-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('animation', '애니메이션'), ('comedy', '코미디'), ('documentary', '다큐멘터리'), ('drama', '드라마'), ('fantasy', '판타지'), ('horror', '호러'), ('musical', '뮤지컬'), ('romance', '로맨스'), ('sf', 'SF'), ('thriller', '스릴러'), ('historical', '사극')], default='', max_length=100),
        ),
    ]
